// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Assert;
import org.junit.Before;
import org.junit.After;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.firefox.FirefoxBinary;
import org.openqa.selenium.firefox.FirefoxOptions;
import org.openqa.selenium.WebElement;

public class StockUpTest {
   
    private WebDriver wd;
    private String host, signIn, logout;
    private String userName;
    private String userPassword;
    
  @Before
  public void setUp() {
    System.setProperty("webdriver.gecko.driver", "geckodriver");
    FirefoxBinary firefoxBinary = new FirefoxBinary();
    FirefoxOptions options = new FirefoxOptions();
    options.setBinary(firefoxBinary);
    options.setHeadless(true);
    wd = new FirefoxDriver(options);
    host = "https://localhost:8181";
    signIn = host + "/faces/common/signIn.xhtml";
    logout = host + "/faces/common/logout.xhtml";
    userName = "JDoe";
    userPassword = "P@ssw0rd";
  }
  @After
  public void shutDown() {
    wd.quit();
  }
  @Test
  public void stockUpTest() {
      
    //Login
    wd.get(signIn);
    WebElement loginVar= wd.findElement(By.name("j_username"));
    loginVar.clear();
    loginVar.sendKeys(userName);
    WebElement loginVar2= wd.findElement(By.name("j_password"));
    loginVar2.clear();
    loginVar2.sendKeys(userPassword);
    wd.findElement(By.xpath("//input[@value='Zaloguj']")).click();
//    Assert.assertTrue(wd.getPageSource().contains("JDoe"));

    //Go to Wyświetalnie stanu
    wd.get(host + "/faces/stock/listStock.xhtml");
    {
      WebElement dropdown = wd.findElement(By.id("j_idt26:productSymbol"));
      dropdown.findElement(By.xpath("//option[@value='5906961196804']")).click();
    }
    wd.findElement(By.xpath("//input[@value='Wyświetl stan']")).click();
    Assert.assertFalse(wd.getPageSource().contains("Dean Corso"));
    
    
    //Go to Zwiększenie stanu
    wd.get(host + "/faces/stock/stockUp.xhtml");

    //Contractor number
    wd.findElement(By.id("StockUpForm:contractorNumber")).click();
    {
      WebElement dropdown = wd.findElement(By.id("StockUpForm:contractorNumber"));
      dropdown.findElement(By.xpath("//option[@value='0048505854759']")).click();
    }

    //Product symbol
    wd.findElement(By.id("StockUpForm:productSymbol")).click();
    {
      WebElement dropdown = wd.findElement(By.id("StockUpForm:productSymbol"));
      dropdown.findElement(By.xpath("//option[@value='5906961196804']")).click();
    }
    
    //Quantity
    WebElement editlocation = wd.findElement(By.id("StockUpForm:quantity"));
    editlocation.click();
    editlocation.clear();
    editlocation.sendKeys("1");
    
    //Location
    wd.findElement(By.id("StockUpForm:locationSymbol")).click();
    {
      WebElement dropdown = wd.findElement(By.id("StockUpForm:locationSymbol"));
      dropdown.findElement(By.xpath("//option[@value='AA-01-02-01']")).click();
    }
    
    //Dodaj do stanu
    wd.findElement(By.xpath("//input[@value='Dodaj do stanu']")).click();
    wd.findElement(By.xpath("//input[@value='Dodaj do stanu']")).click();
    
    //Go to Wyświetalnie stanu
    wd.get(host + "/faces/stock/listStock.xhtml");
    {
      WebElement dropdown = wd.findElement(By.id("j_idt26:productSymbol"));
      dropdown.findElement(By.xpath("//option[@value='5906961196804']")).click();
    }
    wd.findElement(By.xpath("//input[@value='Wyświetl stan']")).click();
    Assert.assertTrue(wd.getPageSource().contains("Dean Corso"));
    
    wd.get(logout);
    wd.findElement(By.xpath("//input[@value='Wyloguj']")).click();
    Assert.assertTrue(wd.getPageSource().contains("Uwierzytelniony użytkownik: brak autoryzacji"));
  }
  
  @Test
  public void stockIssueTest() {
      
    //Login
    wd.get(signIn);
    WebElement loginVar= wd.findElement(By.name("j_username"));
    loginVar.clear();
    loginVar.sendKeys(userName);
    WebElement loginVar2= wd.findElement(By.name("j_password"));
    loginVar2.clear();
    loginVar2.sendKeys(userPassword);
    wd.findElement(By.xpath("//input[@value='Zaloguj']")).click();

    //Go to Wyświetalnie stanu
    wd.get(host + "/faces/stock/listStock.xhtml");
    {
      WebElement dropdown = wd.findElement(By.id("j_idt26:productSymbol"));
      dropdown.findElement(By.xpath("//option[@value='5906961196804']")).click();
    }
    wd.findElement(By.xpath("//input[@value='Wyświetl stan']")).click();
    Assert.assertTrue(wd.getPageSource().contains("Dean Corso"));
    
    //Click Wydanie towaru
    wd.findElement(By.xpath("//input[@value='Wydanie towaru']")).click();
    
    //Quantity
    WebElement editlocation = wd.findElement(By.id("StockIssueForm:quantityToIssue"));
    editlocation.click();
    editlocation.clear();
    editlocation.sendKeys("1");
    
    //Zatwierdź wydanie
    wd.findElement(By.xpath("//input[@value='Zatwierdź wydanie']")).click();

    //Go to Wyświetalnie stanu
    wd.get(host + "/faces/stock/listStock.xhtml");
    {
      WebElement dropdown = wd.findElement(By.id("j_idt26:productSymbol"));
      dropdown.findElement(By.xpath("//option[@value='5906961196804']")).click();
    }
    wd.findElement(By.xpath("//input[@value='Wyświetl stan']")).click();
    Assert.assertFalse(wd.getPageSource().contains("Dean Corso"));
    Assert.assertTrue(wd.getPageSource().contains("Brak stanu dla wybranego produktu"));
    
    wd.get(logout);
    wd.findElement(By.xpath("//input[@value='Wyloguj']")).click();
    Assert.assertTrue(wd.getPageSource().contains("Uwierzytelniony użytkownik: brak autoryzacji"));
  }
}
