/* -
 * Projekt końcowy realizowany w ramach studiów podyplomowych Nowoczesne aplikacje biznesowe Java EE edycja 8
 */

drop table ISSUE;
drop table STOCK;
drop table CONTRACTOR;
drop table LOCATION;
drop table PRODUCT;
drop view AUTHENTICATION_VIEW;
drop table ACCOUNT;
drop table TABLEGENERATOR;

create table ACCOUNT (
ID BIGINT PRIMARY KEY, 
VERSION	INTEGER NOT NULL,
"NAME" VARCHAR(30) NOT NULL,
SURNAME	VARCHAR(50) NOT NULL,
EMAIL	VARCHAR(100) NOT NULL, CONSTRAINT EMAIL_UNIQUE unique (EMAIL),
QUESTION VARCHAR(80) NOT NULL,
ANSWER VARCHAR(30) NOT NULL,
LOGIN VARCHAR(30) NOT NULL, CONSTRAINT LOGIN_UNIQUE unique (LOGIN),
PASSWORD VARCHAR(64) NOT NULL,
ACTIVE SMALLINT NOT NULL,
LEVEL_OF_ACCESS	VARCHAR(31) NOT NULL,
AUTHORIZED_BY BIGINT REFERENCES ACCOUNT(ID),
MODIFICATED_BY BIGINT REFERENCES ACCOUNT(ID),
CREATION_DATE TIMESTAMP NOT NULL,
MODIFICATION_DATE TIMESTAMP);

create table PRODUCT (
ID BIGINT PRIMARY KEY, 
VERSION	INTEGER NOT NULL,
PRODUCT_SYMBOL VARCHAR(13) NOT NULL, CONSTRAINT PRODUCT_UNIQUE unique (PRODUCT_SYMBOL),
DESCRIPTION VARCHAR(500) NOT NULL,
PRICE DECIMAL(8,2) NOT NULL,
WEIGHT_IN_G INTEGER NOT NULL,
EASILY_DAMAGE SMALLINT NOT NULL,
CREATED_BY BIGINT REFERENCES ACCOUNT(ID),
MODIFICATED_BY BIGINT REFERENCES ACCOUNT(ID),
CREATION_DATE TIMESTAMP NOT NULL,
MODIFICATION_DATE TIMESTAMP);

create table LOCATION (
ID BIGINT PRIMARY KEY, 
VERSION	INTEGER NOT NULL,
LOCATION_SYMBOL	CHAR(11) NOT NULL, CONSTRAINT LOCATION_UNIQUE unique (LOCATION_SYMBOL),
MAX_WEIGHT_IN_G	INTEGER	NOT NULL,
EMPTY_LOCATION SMALLINT NOT NULL,
LOCATION_TYPE CHAR(6) NOT NULL,
CREATED_BY BIGINT REFERENCES ACCOUNT(ID),
MODIFICATED_BY BIGINT REFERENCES ACCOUNT(ID),
CREATION_DATE TIMESTAMP NOT NULL,
MODIFICATION_DATE TIMESTAMP);

create table CONTRACTOR (
ID BIGINT PRIMARY KEY, 
VERSION	INTEGER NOT NULL,
CONTRACTOR_NUMBER VARCHAR(15) NOT NULL, CONSTRAINT CONTRACTOR_UNIQUE unique (CONTRACTOR_NUMBER),
COMPANY_NAME_OR_NAME_AND_SURNAME VARCHAR(100) NOT NULL,
NIP VARCHAR(13),
REGON VARCHAR(14),
STREET VARCHAR(50) NOT NULL,
HOUSE VARCHAR(10) NOT NULL,
APARTMENT VARCHAR(10),
ZIP VARCHAR(10)	NOT NULL,
CITY VARCHAR(50) NOT NULL,
ACTIVE	SMALLINT NOT NULL,
CREATED_BY BIGINT REFERENCES ACCOUNT(ID),
MODIFICATED_BY BIGINT REFERENCES ACCOUNT(ID),
CREATION_DATE TIMESTAMP NOT NULL,
MODIFICATION_DATE TIMESTAMP);

create table STOCK (
ID BIGINT PRIMARY KEY, 
VERSION	INTEGER NOT NULL,
QUANTITY INTEGER NOT NULL,
PRODUCT_ID BIGINT REFERENCES PRODUCT(ID),
LOCATION_ID BIGINT REFERENCES LOCATION(ID), CONSTRAINT LOCATION_IN_STOCK_UNIQUE unique (LOCATION_ID),
CONTRACTOR_ID BIGINT REFERENCES CONTRACTOR(ID),
CREATED_BY BIGINT REFERENCES ACCOUNT(ID),
MODIFICATED_BY BIGINT REFERENCES ACCOUNT(ID),
CREATION_DATE TIMESTAMP NOT NULL,
MODIFICATION_DATE TIMESTAMP);

create table ISSUE (
ID BIGINT PRIMARY KEY, 
PRODUCT	VARCHAR(13) NOT NULL,
DESCRIPTION VARCHAR(500) NOT NULL,
PRICE DECIMAL(8,2) NOT NULL,
LOCATION CHAR(11) NOT NULL,
CONTRACTOR VARCHAR(15) NOT NULL,
QUANTITY INTEGER NOT NULL,
CREATED_BY VARCHAR(255) NOT NULL,
CREATION_DATE TIMESTAMP NOT NULL);


create table TABLEGENERATOR (
ID VARCHAR(50) PRIMARY KEY,
VALUE DECIMAL(15,0)
);

CREATE VIEW AUTHENTICATION_VIEW AS 
SELECT login, password, level_of_access FROM ACCOUNT WHERE active>0 AND NOT level_of_access  = 'access.level.newregistered';

